[package]
name = "ollama-tauri-app"
version = "0.1.0"
description = "Ollama Chat with Embedded Python Flask API"
authors = ["Patrick Zhang"]
edition = "2021"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
tauri = { version = "2", features = [] }
windows-sys = "0.61"
tauri-plugin-shell = "2"
tauri-plugin-path = "2"

[build-dependencies]
tauri-build = { version = "2.0", features = [] }
